server:
  grpc_port: ":50051"
  http_port: ":8080"
  environment: "production"
  shutdown_timeout: 30s

database:
  host: "timescaledb"
  port: 5432
  user: "market_user"
  password: "${DB_PASSWORD}"  # Use env var in production
  database: "trading_db"
  ssl_mode: "require"
  max_connections: 25
  conn_max_lifetime: 5m
  listen_channel: "market_data_updates"

redis:
  address: "redis:6379"
  password: "${REDIS_PASSWORD}"  # Use env var in production
  db: 0
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s

logging:
  level: "info"
  format: "json"  # Structured JSON for production
  time_format: "unix"

market:
  vn30_table_name: "vn30_table"
  hnx_table_name: "hnx_table"
  cache_ttl: 24h
  stream_buffer_size: 100
  max_concurrent_connections: 1000
