server:
  grpc_port: ":50051"
  http_port: ":8080"
  environment: "development"
  shutdown_timeout: 30s

database:
  host: "localhost"
  port: 5432
  user: "market_user"
  password: "market_password"
  database: "trading_db"
  ssl_mode: "disable"
  max_connections: 10
  conn_max_lifetime: 5m
  listen_channel: "market_data_updates"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s

logging:
  level: "debug"
  format: "console"  # Human-readable for development
  time_format: "rfc3339"

market:
  vn30_table_name: "vn30_table"
  hnx_table_name: "hnx_table"
  cache_ttl: 1h  # Shorter TTL for development
  stream_buffer_size: 50
  max_concurrent_connections: 100
