/**
 * @fileoverview gRPC-Web generated client stub for market
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.32.1
// source: market.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as market_pb from './market_pb'; // proto import: "market.proto"


export class MarketServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetHistoricalData = new grpcWeb.MethodDescriptor(
    '/market.MarketService/GetHistoricalData',
    grpcWeb.MethodType.UNARY,
    market_pb.HistoricalRequest,
    market_pb.HistoricalResponse,
    (request: market_pb.HistoricalRequest) => {
      return request.serializeBinary();
    },
    market_pb.HistoricalResponse.deserializeBinary
  );

  getHistoricalData(
    request: market_pb.HistoricalRequest,
    metadata?: grpcWeb.Metadata | null): Promise<market_pb.HistoricalResponse>;

  getHistoricalData(
    request: market_pb.HistoricalRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: market_pb.HistoricalResponse) => void): grpcWeb.ClientReadableStream<market_pb.HistoricalResponse>;

  getHistoricalData(
    request: market_pb.HistoricalRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: market_pb.HistoricalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/market.MarketService/GetHistoricalData',
        request,
        metadata || {},
        this.methodDescriptorGetHistoricalData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/market.MarketService/GetHistoricalData',
    request,
    metadata || {},
    this.methodDescriptorGetHistoricalData);
  }

  methodDescriptorStreamMarketData = new grpcWeb.MethodDescriptor(
    '/market.MarketService/StreamMarketData',
    grpcWeb.MethodType.SERVER_STREAMING,
    market_pb.StreamRequest,
    market_pb.MarketData,
    (request: market_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    market_pb.MarketData.deserializeBinary
  );

  streamMarketData(
    request: market_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<market_pb.MarketData> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/market.MarketService/StreamMarketData',
      request,
      metadata || {},
      this.methodDescriptorStreamMarketData);
  }

}

